<?php

namespace Erilshk\Vinti4NetLegacy;

use Exception;
use InvalidArgumentException;

/**
 * Vinti4Net Legacy SDK
 *
 * PHP SDK for integrating with **Vinti4Net (SISP – Cabo Verde)** to process
 * online payments, service payments, mobile top-ups, and refunds.
 *
 * This legacy implementation is fully compatible with **PHP 5.6+**.
 *
 * Supported operations:
 * - Purchase (3D Secure)
 * - Service Payment
 * - Recharge / Top-up
 * - Refund
 *
 * Main features:
 * - Generates auto-submit HTML forms for redirecting the customer to Vinti4Net
 * - Validates and parses gateway responses
 * - Fingerprint generation for request and response integrity
 * - Billing data normalization for 3DS / fraud-prevention
 * - Dynamic Currency Conversion (DCC) support
 *
 * @package   Erilshk\Vinti4Net
 * @author    Erilando TS Carvalho
 * @license   MIT
 * @version   1.0
 */
class Vinti4NetLegacy
{
    /** @var string Default Vinti4Net production URL */
    const DEFAULT_BASE_URL = "https://mc.vinti4net.cv/BizMPIOnUsSisp/CardPayment";

    /** @var string Payment type: Purchase */
    const TRANSACTION_TYPE_PURCHASE = '1';

    /** @var string Payment type: Service */
    const TRANSACTION_TYPE_SERVICE  = '2';

    /** @var string Payment type: Recharge */
    const TRANSACTION_TYPE_RECHARGE = '3';

    /** @var string Payment type: Refund */
    const TRANSACTION_TYPE_REFUND   = '4';

    /** @var string Default currency code (CVE – Cape Verde Escudo) */
    const CURRENCY_CVE = '132';

    /** @var array Message types that represent successful transactions */
    const SUCCESS_MESSAGE_TYPES = ['8', '10', 'P', 'M'];

    /** @var string POS Identifier provided by SISP */
    private $posID;

    /** @var string POS authentication code provided by SISP */
    private $posAuthCode;

    /** @var string Gateway base URL */
    private $baseUrl;

    /** @var array Internal request data structure */
    private $request = [];

    /** @var bool Indicates if the payment request was already prepared */
    private $prepared = false;

    /**
     * Constructor
     *
     * Initializes a new Vinti4Net client with the required POS credentials.
     *
     * @param string      $posID        POS ID provided by SISP.
     * @param string      $posAuthCode  POS authentication code provided by SISP.
     * @param string|null $endpoint     Optional base endpoint URL. Defaults to the production gateway.
     *
     * @example
     * $vinti4 = new Vinti4NetLegacy('POS123', 'ABCD1234');
     *
     * @return void
     */
    public function __construct($posID, $posAuthCode, $endpoint = null)
    {
        $this->posID = $posID;
        $this->posAuthCode = $posAuthCode;
        $this->baseUrl = $endpoint ? $endpoint : self::DEFAULT_BASE_URL;
    }


    /**
     * Sets additional optional parameters for the payment request.
     *
     * This method allows manually configuring values that are not automatically
     * set during payment preparation. Only recognized and allowed keys may be provided —
     * any invalid key will throw an InvalidArgumentException.
     *
     * The list of allowed fields reflects the parameters accepted by SISP/Vinti4Net:
     *
     * - merchantRef          Unique order identifier generated by the merchant.
     * - merchantSession      Merchant session ID.
     * - languageMessages     Language for messages displayed to the user (e.g., 'en', 'pt', 'fr').
     * - entityCode           Payment entity (for services or top-ups).
     * - referenceNumber      Payment reference (for services or top-ups).
     * - timeStamp            Request date/time (Y-m-d H:i:s).
     * - billing              Full billing / 3DS customer data.
     * - currency             Currency code (ISO3 or numeric). Automatically converted if ISO3.
     * - acctID               Customer account identifier.
     * - acctInfo             3DS account history data.
     * - addrMatch            Indicates whether delivery address matches billing address.
     * - billAddrCountry      Billing country.
     * - billAddrCity         Billing city.
     * - billAddrLine1        Address line 1 (required for purchases).
     * - billAddrPostCode     Postal code.
     * - email                Customer email address.
     * - clearingPeriod       Clearing period (used for REFUND requests).
     *
     * If the "currency" parameter is provided as an ISO3 string (e.g., "CVE", "EUR", "USD"),
     * it will be automatically converted to the corresponding numeric code.
     *
     * @param array $params  List of optional parameters to set.
     *
     * @return $this  Returns the instance to allow method chaining.
     *
     * @throws InvalidArgumentException If any provided parameter is not allowed.
     */
    public function setRequestParams(array $params)

    {
        $allowed = [
            'merchantRef',
            'merchantSession',
            'languageMessages',
            'entityCode',
            'referenceNumber',
            'timeStamp',
            'billing',
            'currency',
            'acctID',
            'acctInfo',
            'addrMatch',
            'billAddrCountry',
            'billAddrCity',
            'billAddrLine1',
            'billAddrPostCode',
            'email',
            'clearingPeriod',
        ];

        foreach ($params as $key => $value) {
            if (!in_array($key, $allowed, true)) {
                throw new InvalidArgumentException("Parâmetro não permitido: {$key}");
            }
            if ($key == 'currency') {
                $value = $this->currencyToCode($value);
            }
            $this->request[$key] = $value;
        }

        return $this;
    }

    /**
     * Prepares a **purchase (3DS)** payment request.
     *
     * This method sets up all the necessary data to initiate a purchase transaction with 3D Secure authentication.
     * It builds the internal payload that will later be converted into a payment form.
     *
     * The `$billing` array may contain direct fields or a `user` sub-array, which will be automatically normalized:
     * - Required fields: `email`, `billAddrCountry`, `billAddrCity`, `billAddrLine1`, `billAddrPostCode`.
     * - Optional fields: `billAddrLine2`, `billAddrLine3`, `billAddrState`, `mobilePhone`, `workPhone`, `acctID`.
     * - The `user` sub-array may include: `id`, `created_at`, `updated_at`, `suspicious`, `phone`, `mobilePhoneCC`, `workPhoneCC`, etc.
     *
     * @param float|int $amount   Transaction amount (in escudos or the configured currency).
     * @param array     $billing  Customer billing data.
     * @param string|int $currency Currency code (default: 'CVE' or equivalent numeric code).
     *
     * @return $this Returns the instance to allow method chaining (fluent interface).
     *
     * @throws InvalidArgumentException If any required data is missing or invalid during internal preparation.
     *
     * @example
     * $vinti4->preparePurchasePayment(1500, [
     *     'user' => [
     *         'email' => 'customer@example.com',
     *         'country' => '132',
     *         'city' => 'Praia',
     *         'mobilePhone' => '+23899123456'
     *     ]
     * ]);
     */
    public function preparePurchasePayment($amount, array $billing, $currency = 'CVE')
    {
        $this->preparePaymentRequest([
            'amount' => $amount,
            'transactionCode' => self::TRANSACTION_TYPE_PURCHASE,
            'currency' => $currency,
            'billing' => $billing,
        ]);
        return $this;
    }


    /**
     * Prepares a **service** payment request.
     *
     * Used for service payments with an entity code and reference number.
     *
     * @param float|int  $amount  Transaction amount.
     * @param string|int $entity  Service entity code.
     * @param string|int $number  Reference number of the service transaction.
     *
     * @return $this Returns the instance to allow method chaining (fluent interface).
     *
     * @throws InvalidArgumentException If any required data is missing or invalid.
     */
    public function prepareServicePayment($amount, $entity, $number)
    {
        $this->preparePaymentRequest([
            'amount' => $amount,
            'transactionCode' => self::TRANSACTION_TYPE_SERVICE,
            'entityCode' => $entity,
            'referenceNumber' => $number
        ]);
        return $this;
    }

    /**
     * Prepares a **recharge** payment request.
     *
     * Used for recharging accounts, cards, or phones with an entity code and reference number.
     *
     * @param float|int  $amount  Recharge amount.
     * @param string|int $entity  Recharge entity code.
     * @param string|int $number  Reference number of the recharge.
     *
     * @return $this Returns the instance to allow method chaining (fluent interface).
     *
     * @throws InvalidArgumentException If any required data is missing or invalid.
     */
    public function prepareRechargePayment($amount, $entity, $number)
    {
        $this->preparePaymentRequest([
            'amount' => $amount,
            'transactionCode' => self::TRANSACTION_TYPE_RECHARGE,
            'entityCode' => $entity,
            'referenceNumber' => $number
        ]);
        return $this;
    }

    /**
     * Prepares a **refund** payment request.
     *
     * This method is used to reverse a previously approved transaction.
     * It requires the merchant ID, session, original transaction ID, and clearing period.
     *
     * @param float|int  $amount          Refund amount (must be an integer in currency units, no decimals for SISP).
     * @param string      $merchantRef     Unique identifier of the original order in the merchant system.
     * @param string      $merchantSession Identifier of the original order session.
     * @param string      $transactionID   ID of the transaction to be refunded.
     * @param string|int  $clearingPeriod  Clearing period related to the refund.
     *
     * @return $this Returns the instance to allow method chaining (fluent interface).
     *
     * @throws InvalidArgumentException If any required data is missing or invalid.
     */
    public function prepareRefundPayment($amount, $merchantRef, $merchantSession, $transactionID, $clearingPeriod)
    {
        $this->preparePaymentRequest([
            'transactionCode'   => self::TRANSACTION_TYPE_REFUND,
            'amount'            => $amount,
            'clearingPeriod'    => $clearingPeriod,
            'transactionID'     => $transactionID,
            'merchantRef'       => $merchantRef,
            'merchantSession'   => $merchantSession,
        ]);

        return $this;
    }


    /**
     * Generates an **HTML payment form** with auto-submit to initiate the transaction on Vinti4Net.
     *
     * This method builds an HTML form with hidden fields containing all necessary transaction data,
     * including the security fingerprint. When the page loads, the form is automatically submitted
     * to the gateway URL.
     *
     * @param string      $responseUrl   URL to which the gateway should send the transaction response.
     * @param string|null $merchantRef   Optional. Unique merchant reference to identify the transaction.
     *
     * @return string HTML markup of the form with auto-submit.
     *
     * @throws InvalidArgumentException If any required parameter is missing or invalid.
     */
    public function createPaymentForm($responseUrl, $merchantRef = null)
    {
        $this->request['urlMerchantResponse'] = $responseUrl;
        if ($merchantRef !== null) {
            $this->request['merchantRef'] = $merchantRef;
        }

        $paymentData = $this->processRequest($this->request);

        $fields = '';
        foreach ($paymentData['fields'] as $k => $v) {
            $fields .= "<input type='hidden' name='{$k}' value='" . htmlspecialchars((string)$v) . "'>\n";
        }

        return "
        <html>
        <head><title>Pagamento Vinti4Net</title></head>
        <body onload='document.forms[0].submit()'>
            <form method='post' action='{$paymentData['postUrl']}'>
                {$fields}
            </form>
            <p>processando...</p>
        </body>
        </html>";
    }

    /**
     * Processes the response sent by Vinti4Net after a payment.
     *
     * This method validates the response received from the gateway, checks if the user canceled
     * the transaction, computes the fingerprint to ensure data integrity, and extracts additional
     * information such as DCC (Dynamic Currency Conversion) when applicable.
     *
     * The returned response has the following structure:
     * - `status` (string): Transaction status (`SUCCESS`, `ERROR`, `CANCELLED`, `INVALID_FINGERPRINT`).
     * - `message` (string): Descriptive status message.
     * - `success` (bool): Indicates whether the transaction was successfully processed.
     * - `data` (array): Raw data received from the gateway.
     * - `dcc` (array): Dynamic currency conversion information (if applicable), including:
     *     - `enabled` (bool)
     *     - `amount` (float|null)
     *     - `currency` (string|null)
     *     - `markup` (float|null)
     *     - `rate` (float|null)
     * - `debug` (array): Debug information, especially if the fingerprint is invalid.
     * - `detail` (string|null): Additional error details, if any.
     *
     * @param array $postData Data received via POST from the Vinti4Net gateway.
     *
     * @return array{
     *     status: string,
     *     message: string,
     *     success: bool,
     *     data: array,
     *     dcc: array,
     *     debug: array,
     *     detail: string|null
     * }
     *
     * @example
     * $response = $vinti4->processResponse($_POST);
     * if ($response['status'] === 'SUCCESS') {
     *     echo "Payment completed successfully!";
     * } elseif ($response['status'] === 'CANCELLED') {
     *     echo "User canceled the transaction.";
     * } else {
     *     echo "Payment failed: " . $response['message'];
     * }
     */
    public function processResponse(array $postData)
    {
        $result = [
            'status' => 'ERROR',
            'message' => 'Erro desconhecido na transação.',
            'success' => false,
            'data' => $postData,
            'dcc' => [],
            'debug' => [],
            'detail' => ''
        ];

        if (isset($postData['UserCancelled']) && $postData['UserCancelled'] === 'true') {
            $result['status'] = 'CANCELLED';
            $result['message'] = 'Utilizador cancelou a transação.';
            return $result;
        }

        if (isset($postData['messageType']) && in_array($postData['messageType'], self::SUCCESS_MESSAGE_TYPES, true)) {

            $finger = $this->fingerprintResponse($postData);
            $fingerValid = isset($postData['resultFingerPrint']) && $postData['resultFingerPrint'] === $finger;
            $result['success'] = $fingerValid;

            $result['status'] = $fingerValid ? 'SUCCESS' : 'INVALID_FINGERPRINT';
            $result['message'] = $fingerValid ? 'Transação válida.' : 'Fingerprint inválido.';

            if (!$fingerValid) {
                $result['debug'] = [
                    'recebido' => isset($postData['resultFingerPrint']) ? $postData['resultFingerPrint'] : '',
                    'calculado' => $finger
                ];
            }

            if (!empty($postData['merchantRespDCCData'])) {
                $dcc = json_decode($postData['merchantRespDCCData'], true);
                if (json_last_error() === JSON_ERROR_NONE && is_array($dcc)) {
                    $result['dcc'] = [
                        'enabled' => isset($dcc['dcc']) && $dcc['dcc'] === 'Y',
                        'amount'  => isset($dcc['dccAmount']) ? $dcc['dccAmount'] : null,
                        'currency' => isset($dcc['dccCurrency']) ? $dcc['dccCurrency'] : null,
                        'markup'  => isset($dcc['dccMarkup']) ? $dcc['dccMarkup'] : null,
                        'rate'    => isset($dcc['dccRate']) ? $dcc['dccRate'] : null
                    ];
                }
            }

            return $result;
        }

        $result['message'] = isset($postData['merchantRespErrorDescription'])
            ? $postData['merchantRespErrorDescription']
            : 'Transação falhou.';

        $result['detail'] = isset($postData['merchantRespErrorDetail'])
            ? $postData['merchantRespErrorDetail']
            : null;

        return $result;
    }

    /**
     * Prepares the internal structure of the request.
     *
     * @param array $params Parameters to configure the request.
     *
     * @return void
     *
     * @throws Exception If an error occurs during preparation.
     */
    private function preparePaymentRequest(array $params)
    {
        if ($this->prepared) {
            throw new Exception("Vinti4Net: ONLY 1 PAYMENT REQUEST MUST BE PREPARED");
        }

        $this->request = [
            'posID' => $this->posID,
            'merchantRef' => isset($params['merchantRef']) ? $params['merchantRef'] : 'R' . date('YmdHis'),
            'merchantSession' => isset($params['merchantSession']) ? $params['merchantSession'] : 'S' . date('YmdHis'),
            'amount' => (int)(float)$params['amount'],
            'currency' => $this->currencyToCode(isset($params['currency']) ? $params['currency'] : self::CURRENCY_CVE),
            'transactionCode' => isset($params['transactionCode']) ? $params['transactionCode'] : self::TRANSACTION_TYPE_PURCHASE,
            'languageMessages' => isset($params['languageMessages']) ? $params['languageMessages'] : 'pt',
            'entityCode' => isset($params['entityCode']) ? $params['entityCode'] : '',
            'referenceNumber' => isset($params['referenceNumber']) ? $params['referenceNumber'] : '',
            'timeStamp' => date('Y-m-d H:i:s'),
            'fingerprintversion' => '1',
            'is3DSec' => '1',
            'urlMerchantResponse' => isset($params['urlMerchantResponse']) ? $params['urlMerchantResponse'] : '',
            'billing' => isset($params['billing']) ? $params['billing'] : []
        ];

        $this->prepared = true;
    }

    /**
     * Builds the final fields to be sent via POST to the SISP gateway.
     *
     * @param array $fields Input fields to include in the request.
     *
     * @return array{postUrl: string, fields: array} Returns the POST URL and the prepared fields.
     */
    private function processRequest(array $fields)
    {
        if ($fields['transactionCode'] === self::TRANSACTION_TYPE_PURCHASE && !empty($fields['billing'])) {
            $fields['purchaseRequest'] = $this->generatePurchaseRequest($fields['billing']);
            $fields = array_merge($fields, $fields['billing']);
        }

        $type = $fields['transactionCode'] != self::TRANSACTION_TYPE_REFUND ? 'payment' : 'refund';

        unset($fields['billing']);

        $fields['fingerprint'] = $this->fingerprintRequest($fields, $type);

        $postUrl = $this->baseUrl . '?' . http_build_query([
            'FingerPrint' => $fields['fingerprint'],
            'TimeStamp' => $fields['timeStamp'],
            'FingerPrintVersion' => $fields['fingerprintversion']
        ]);

        return [
            'postUrl' => $postUrl,
            'fields' => $fields
        ];
    }

    /**
     * Normalizes the billing data for submission to the SISP gateway.
     *
     * @param array $billing Billing information to be normalized.
     *
     * @return array Normalized billing data ready for the request.
     */
    private function normalizeBilling(array $billing)
    {
        $user = isset($billing['user']) ? $billing['user'] : [];
        unset($billing['user']);

        $get = function ($src, $key, $default = null) {
            if (is_array($src)) {
                return isset($src[$key]) ? $src[$key] : $default;
            }
            return isset($src->$key) ? $src->$key : $default;
        };

        $extractCC = function ($phone, $default = '238') {
            $phone = preg_replace('/\D+/', '', $phone);
            if (preg_match('/^(?:\+|00)?(\d{1,3})/', $phone, $m)) {
                return $m[1];
            }
            return $default;
        };

        $email    = isset($billing['email']) ? $billing['email'] : $get($user, 'email');
        $country  = isset($billing['billAddrCountry']) ? $billing['billAddrCountry'] : $get($user, 'country', '132');
        $city     = isset($billing['billAddrCity']) ? $billing['billAddrCity'] : $get($user, 'city', '');
        $line1    = isset($billing['billAddrLine1']) ? $billing['billAddrLine1'] : $get($user, 'address', '');
        $line2    = isset($billing['billAddrLine2']) ? $billing['billAddrLine2'] : $get($user, 'address2', '');
        $line3    = isset($billing['billAddrLine3']) ? $billing['billAddrLine3'] : $get($user, 'address3', '');
        $postcode = isset($billing['billAddrPostCode']) ? $billing['billAddrPostCode'] : $get($user, 'postCode', '');
        $state    = isset($billing['billAddrState']) ? $billing['billAddrState'] : $get($user, 'state');

        $mobile = isset($billing['mobilePhone']) ? $billing['mobilePhone'] : $get($user, 'mobilePhone', $get($user, 'phone'));
        $work   = isset($billing['workPhone']) ? $billing['workPhone'] : $get($user, 'workPhone');

        $mobilePhone = $mobile ? [
            'cc' => $get($user, 'mobilePhoneCC', $extractCC($mobile)),
            'subscriber' => preg_replace('/\D+/', '', $mobile)
        ] : null;

        $workPhone = $work ? [
            'cc' => $get($user, 'workPhoneCC', $extractCC($work)),
            'subscriber' => preg_replace('/\D+/', '', $work)
        ] : null;

        $acctID      = $get($user, 'id');
        $createdAt   = $get($user, 'created_at');
        $updatedAt   = $get($user, 'updated_at');
        $suspicious  = $get($user, 'suspicious');

        $chAccAgeInd = $get($user, 'chAccAgeInd', ($createdAt ? '05' : '01'));
        $chAccPwInd  = $get($user, 'chAccPwChangeInd', ($updatedAt ? '05' : '01'));

        $acctInfo = [
            'chAccAgeInd' => $chAccAgeInd,
            'chAccChange' => $updatedAt ? date('Ymd', strtotime($updatedAt)) : '',
            'chAccDate' => $createdAt ? date('Ymd', strtotime($createdAt)) : '',
            'chAccPwChange' => $updatedAt ? date('Ymd', strtotime($updatedAt)) : '',
            'chAccPwChangeInd' => $chAccPwInd,
            'suspiciousAccActivity' => isset($suspicious) ? ($suspicious ? '02' : '01') : ''
        ];

        foreach ($acctInfo as $k => $v) {
            if ($v === '') unset($acctInfo[$k]);
        }

        $data = [
            'email'            => $email,
            'billAddrCountry'  => $country,
            'billAddrCity'     => $city,
            'billAddrLine1'    => $line1,
            'billAddrLine2'    => $line2,
            'billAddrLine3'    => $line3,
            'billAddrPostCode' => $postcode,
            'billAddrState'    => $state,
            'mobilePhone'      => $mobilePhone,
            'workPhone'        => $workPhone,
            'acctID'           => $acctID,
            'acctInfo'         => !empty($acctInfo) ? $acctInfo : null,
        ];

        foreach ($data as $k => $v) {
            if ($v === null || $v === '') unset($data[$k]);
        }

        return $data;
    }

    /**
     * Converts an ISO currency code to the SISP numeric code.
     *
     * @param string|int $currency ISO 4217 currency code (e.g., 'CVE', 'USD') or numeric code.
     *
     * @return int Corresponding numeric code used by SISP.
     *
     * @throws InvalidArgumentException If the provided currency is invalid or unsupported.
     */

    private function currencyToCode($currency)
    {
        $currency = strtoupper($currency);

        switch ($currency) {
            case 'CVE':
                return 132;
            case 'USD':
                return 840;
            case 'EUR':
                return 978;
            case 'BRL':
                return 986;
            case 'GBP':
                return 826;
            case 'JPY':
                return 392;
            case 'CNY':
                return 156;
        }

        if (is_numeric($currency)) {
            return (int)$currency;
        }

        throw new InvalidArgumentException("Invalid currency code: $currency");
    }

    /**
     * Calculates the fingerprint for the request.
     *
     * @param array $data Data of the request to hash.
     * @param string $type Type of request: 'payment' or 'refund'.
     *
     * @return string Base64-encoded SHA512 hash of the request data.
     */
    private function fingerprintRequest(array $data, $type = 'payment')
    {
        $encodedPOSAuthCode = base64_encode(hash('sha512', $this->posAuthCode, true));

        // ------------------------------------------------------
        // PAYMENT
        // ------------------------------------------------------
        if ($type === 'payment') {

            $amount = isset($data['amount']) ? (float)$data['amount'] : 0;
            $amountLong = (int)bcmul($amount, '1000', 0);

            $entity = !empty($data['entityCode']) ? (int)$data['entityCode'] : '';
            $reference = !empty($data['referenceNumber']) ? (int)$data['referenceNumber'] : '';

            $toHash = $encodedPOSAuthCode .
                (isset($data['timeStamp']) ? $data['timeStamp'] : '') .
                $amountLong .
                (isset($data['merchantRef']) ? $data['merchantRef'] : '') .
                (isset($data['merchantSession']) ? $data['merchantSession'] : '') .
                (isset($data['posID']) ? $data['posID'] : '') .
                (isset($data['currency']) ? $data['currency'] : '') .
                (isset($data['transactionCode']) ? $data['transactionCode'] : '') .
                $entity .
                $reference;

            return base64_encode(hash('sha512', $toHash, true));
        }

        // ------------------------------------------------------
        // REFUND
        // ------------------------------------------------------
        if ($type === 'refund') {

            // amount deve ser inteiro
            $amount = isset($data['amount']) ? (string)$data['amount'] : '';
            if (!preg_match('/^\d+$/', $amount)) {
                throw new InvalidArgumentException("Amount deve ser inteiro, sem casas decimais.");
            }

            $toHash = $encodedPOSAuthCode .
                (isset($data['posID']) ? $data['posID'] : '') .
                (isset($data['merchantRef']) ? $data['merchantRef'] : '') .
                (isset($data['merchantSession']) ? $data['merchantSession'] : '') .
                $amount .
                (isset($data['currency']) ? $data['currency'] : '') .
                (isset($data['transactionCode']) ? $data['transactionCode'] : '') .
                (isset($data['reversal']) ? $data['reversal'] : ''); // 'R'

            return base64_encode(hash('sha512', $toHash, true));
        }

        throw new InvalidArgumentException("Invalid fingerprint type: {$type}");
    }


    /**
     * Calculates the fingerprint for the response sent by the SISP gateway.
     *
     * @param array $data Response data to validate.
     * @param string $type Type of response: 'payment' or 'refund'.
     *
     * @return string Base64-encoded SHA512 hash of the response data.
     */
    private function fingerprintResponse(array $data, $type = 'payment')
    {
        $encodedPOSAuthCode = base64_encode(hash('sha512', $this->posAuthCode, true));

        // ------------------------------------------------------
        // PAYMENT
        // ------------------------------------------------------
        if ($type === 'payment') {

            $amount = isset($data["merchantRespPurchaseAmount"]) ? (float)$data["merchantRespPurchaseAmount"] : 0;
            $amountLong = (int)bcmul($amount, '1000', 0);

            $toHash =
                $encodedPOSAuthCode .
                (isset($data["messageType"]) ? $data["messageType"] : '') .
                (isset($data["merchantRespCP"]) ? $data["merchantRespCP"] : '') .
                (isset($data["merchantRespTid"]) ? $data["merchantRespTid"] : '') .
                (isset($data["merchantRespMerchantRef"]) ? $data["merchantRespMerchantRef"] : '') .
                (isset($data["merchantRespMerchantSession"]) ? $data["merchantRespMerchantSession"] : '') .
                $amountLong .
                (isset($data["merchantRespMessageID"]) ? $data["merchantRespMessageID"] : '') .
                (isset($data["merchantRespPan"]) ? $data["merchantRespPan"] : '') .
                (isset($data["merchantResp"]) ? $data["merchantResp"] : '') .
                (isset($data["merchantRespTimeStamp"]) ? $data["merchantRespTimeStamp"] : '') .
                (isset($data['merchantRespReferenceNumber']) && $data['merchantRespReferenceNumber'] !== '' ? (int)$data['merchantRespReferenceNumber'] : '') .
                (isset($data['merchantRespEntityCode']) && $data['merchantRespEntityCode'] !== '' ? (int)$data['merchantRespEntityCode'] : '') .
                (isset($data["merchantRespClientReceipt"]) ? $data["merchantRespClientReceipt"] : '') .
                trim(isset($data["merchantRespAdditionalErrorMessage"]) ? $data["merchantRespAdditionalErrorMessage"] : '') .
                (isset($data["merchantRespReloadCode"]) ? $data["merchantRespReloadCode"] : '');

            return base64_encode(hash('sha512', $toHash, true));
        }

        // ------------------------------------------------------
        // REFUND
        // ------------------------------------------------------
        if ($type === 'refund') {

            $amount = isset($data['merchantRespPurchaseAmount'])
                ? (int)$data['merchantRespPurchaseAmount']
                : 0;

            $toHash =
                $encodedPOSAuthCode .
                (isset($data["messageType"]) ? $data["messageType"] : '') .
                (isset($data["merchantRespClearingPeriod"]) ? $data["merchantRespClearingPeriod"] : '') .
                (isset($data["merchantRespTransactionID"]) ? $data["merchantRespTransactionID"] : '') .
                (isset($data["merchantRespMerchantRef"]) ? $data["merchantRespMerchantRef"] : '') .
                (isset($data["merchantRespMerchantSession"]) ? $data["merchantRespMerchantSession"] : '') .
                $amount .
                (isset($data["merchantRespMessageID"]) ? $data["merchantRespMessageID"] : '') .
                (isset($data["merchantResp"]) ? $data["merchantResp"] : '') .
                (isset($data["merchantRespTimeStamp"]) ? $data["merchantRespTimeStamp"] : '');

            return base64_encode(hash('sha512', $toHash, true));
        }

        throw new InvalidArgumentException("Invalid fingerprint type: {$type}");
    }


    /**
     * Generates the Base64-encoded JSON for the billing section.
     *
     * @param array $billing Billing data to encode.
     *
     * @return string Base64-encoded JSON string.
     *
     * @throws InvalidArgumentException If the billing data is invalid or incomplete.
     */
    private function generatePurchaseRequest(array $billing)
    {
        $required = ['billAddrCountry', 'billAddrCity', 'billAddrLine1', 'billAddrPostCode', 'email'];

        $billing = $this->normalizeBilling($billing);

        foreach ($required as $key) {
            if (!isset($billing[$key]) || $billing[$key] === '') {
                throw new InvalidArgumentException("Campo obrigatório ausente em billing: {$key}");
            }
        }

        $json = json_encode($billing, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if ($json === false) {
            throw new InvalidArgumentException("Erro ao gerar JSON de billing.");
        }

        return base64_encode($json);
    }
}
